### ISSUE TITLE
Q: real time production/data

### ISSUE THREAD

**Issue by pergolafabio** [rcasula/kostalpiko-homeassistant#19]
Hey @rcasula 

I had before an energy monitor with clamps to measure my production coming from the postal Piko, it was realtime... But the monitor went dead...
Gonna use your component now to monitor ... How correct is it? Because you just poll on an interval? ..

Is there also a way to poll historical data? Or maybe from the online portal from kostal itself?

**Comment by rcasula** [comment]
Hi @pergolafabio, 
Regarding the correctness of data, the library does not do any intelligence whatsoever so ever. It just gets the data from the online portal and then the data gets parsed. 
As far as I know, the data is correct as the PIKO reports it. It is true that the component polls at an interval, but at a specific time point the data is what it's reported by PIKO. 

Regarding historical data I've never tried to get it, in the past i've used the windows program, but when you download the data from the PIKO, the data is then deleted from the inverter. This is because the inverted keeps only (I believe) 3 months of data and then it's rotated

**Comment by pergolafabio** [comment]
ah ok, at what interval do you poll? is it quite accurate if you compare it on month base?

**Comment by rcasula** [comment]
If I remember correctly, this is the param that is used: 

MIN_TIME_BETWEEN_UPDATES = timedelta(seconds=30)

So should be 30s

**Comment by pergolafabio** [comment]
ok ; that should be quite accurate then
have you compared the production in HA on moth/year basis compared the invertor itself?

**Comment by pergolafabio** [comment]
btw, have you tried getting data from: https://www.kostal-solar-portal.com/

i have enabled export to portal on my piko 5.5 , i think this data is quite accurate, i think its been uploaded once a day

Too bad i dont know the consumption, is there some sort of extra module for it?

![image](https://user-images.githubusercontent.com/43251136/206522913-28e9f777-3f54-49ba-a9db-c0e0a9a428b5.png)
